name: Atoum's website
highlighter: pygments
timezone: Europe/Paris
exclude:
  - docker-compose.yml
  - vendor
  - Gemfile
  - Gemfile.lock

markdown: kramdown
kramdown:
    parse_block_html: true
    parse_span_html: true

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sass-converter

feed:
  path: atom.xml

jekyll-mentions:
  base_url: https://github.com

sass:
  sass_dir: _sass
  style: compressed
